services:

  db:
    image: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - /root/fastapi_app/.env # POSTGRES_PASSWORD
    volumes:
      - ../postresql_backup:/var/lib/postgresql/data
    # command: -p 5433
    # expose:
    #   - 5433
    # https://hub.docker.com/_/postgres

  redis:
    image: redis
    container_name: redis
    # command: --port 6377
    # expose:
    #   - 6377
    # https://hub.docker.com/_/redis

  app:
    build:
      context: .
    container_name: fastapi-app
    env_file:
      - /root/fastapi_app/.env
    # turn off 'ports' with nginx service
    # ports:
    #   - 9999:8000
    depends_on:
      - db
      - redis
    command: ["/fastapi-app/scripts/app.sh"]

  celery:
    build:
      context: .
    container_name: celery
    env_file:
      - /root/fastapi_app/.env
    depends_on:
      - redis
    command: ["/fastapi-app/scripts/celery.sh"]
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.001'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.0001'
    #       memory: 20M

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /root/fastapi_app/nginx:/etc/nginx/conf.d/
    depends_on:
      - app



# docker compose build

# docker compose up -d

