services:

  # https://hub.docker.com/_/postgres
  db:
    image: postgres
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    env_file:
      - /root/fastapi/.env # POSTGRES_PASSWORD
    volumes:
      - /root/fastapi_backup:/var/lib/postgresql/data
    # command: -p 5433
    # expose:
    #   - 5433

  # https://hub.docker.com/_/redis
  redis:
    image: redis
    container_name: redis
    # command: --port 6377
    # expose:
    #   - 6377

  app:
    build:
      context: .
    container_name: fastapi-app
    env_file:
      - /root/fastapi/.env
    # turn off 'ports' with nginx service
    # ports:
    #   - 9999:8000
    depends_on:
      - db
      - redis
    volumes:
      - static-vol:/fastapi-app/src/static
    command: ["/fastapi-app/scripts/app.sh"]

  celery:
    build:
      context: .
    container_name: celery
    env_file:
      - /root/fastapi/.env
    depends_on:
      - redis
    command: ["/fastapi-app/scripts/celery.sh"]
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.001'
    #       memory: 50M
    #     reservations:
    #       cpus: '0.0001'
    #       memory: 20M

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - /root/fastapi/nginx.conf:/etc/nginx/conf.d/default.conf
      - static-vol:/static
    depends_on:
      - app
    environment:
      - APP_HOST="http://app:8000"

volumes:
  static-vol:


# docker compose build

# docker compose up -d --build
