"""populate

Revision ID: 2a7ec0796dbd
Revises: 1b83f85e8eba
Create Date: 2024-03-15 11:44:07.177116

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2a7ec0796dbd"
down_revision: Union[str, None] = "1b83f85e8eba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

sql = """INSERT INTO "status" ("name") 
         VALUES ('user'), ('admin'), ('moderator');"""


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sql)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""DELETE FROM "status";""")
    # ### end Alembic commands ###
